"""
report.significance — Statistical significance testing for semantic regression.

Computes one-sided Wilcoxon signed-rank tests comparing observed per-epoch
balanced accuracy against the internal shuffled null, at the best time bin
per patient x embedding. P-values are Bonferroni-corrected across all tests.

The shuffled null is generated by ``semantic_regression.py`` via:
    X_train_shuffle = np.random.permutation(X_train.flatten()).reshape(X_train.shape)
This preserves all pipeline biases (Nystroem, Ridge shrinkage, PCA, retrieval),
so the test isolates the contribution of real neural signal.
"""

import os
import numpy as np
import pandas as pd
from scipy import stats
from .config import EMBEDDING_NAMES, SEM_MODELS
from .loader import load_patient_from_pkl, load_patient_from_csv


def compute_significance(run_dir, fig_dir=None):
    """
    Compute significance for all patients in a run.

    Parameters
    ----------
    run_dir : str
        Path to the run's results directory, containing one subfolder per patient.
        Example: ``results/semantic_regression/2026-03-27_KRR_l2_50ep/``
    fig_dir : str or None
        Path to the run's figures directory (for HTML null extraction fallback).

    Returns
    -------
    pd.DataFrame
        One row per patient x embedding, with columns:
        patient, embedding, model_type, n_epochs,
        mean_cat_obs, mean_cat_null, cat_best_bin, cat_diff_mean, cat_pval_raw,
        mean_word_obs, mean_word_null, word_best_bin, word_diff_mean, word_pval_raw,
        cat_pval_bonf, word_pval_bonf, cat_sig, word_sig, cat_sig_raw, word_sig_raw
    """
    patients = sorted([
        d for d in os.listdir(run_dir)
        if os.path.isdir(os.path.join(run_dir, d)) and d != '__pycache__'
           and not d.endswith('.json')
    ])
    print(f"[Significance] {len(patients)} patients: {patients}")

    raw_records = []

    for patient in patients:
        pkl_path = os.path.join(run_dir, patient, 'semantic_regression_results.pkl')
        pkl_data = None

        # Try PKL first (has per-epoch null arrays)
        if os.path.exists(pkl_path):
            try:
                pkl_data = load_patient_from_pkl(pkl_path)
                if pkl_data is not None:
                    print(f"  {patient}: loaded from PKL", flush=True)
            except Exception as e:
                print(f"  {patient}: PKL error ({e})", flush=True)

        # Fallback to CSV + HTML null
        if pkl_data is None:
            pkl_data = load_patient_from_csv(run_dir, patient, fig_dir)
            if pkl_data is not None:
                print(f"  {patient}: loaded from CSV (fallback)", flush=True)
            else:
                print(f"  {patient}: no data found, skipping", flush=True)
                continue

        for emb in EMBEDDING_NAMES:
            if emb not in pkl_data:
                continue
            d = pkl_data[emb]

            if d.get('from_csv'):
                # CSV path: obs array vs scalar null mean
                cat_obs_at_best  = d['obs_cat_at_best']
                word_obs_at_best = d['obs_word_at_best']
                cat_null_mean    = d['null_cat_mean']
                word_null_mean   = d['null_word_mean']
                cat_best_bin     = d['cat_best_bin']
                word_best_bin    = d['word_best_bin']
                n_epochs = len(cat_obs_at_best)

                _, cat_pval  = stats.wilcoxon(
                    cat_obs_at_best - cat_null_mean, alternative='greater')
                _, word_pval = stats.wilcoxon(
                    word_obs_at_best - word_null_mean, alternative='greater')
            else:
                # PKL path: paired obs vs null per-epoch arrays
                cat_obs  = np.array(d['cat_obs'])    # (n_epochs, n_bins)
                cat_null = np.array(d['cat_null'])
                word_obs  = np.array(d['word_obs'])
                word_null = np.array(d['word_null'])

                cat_best_bin  = int(np.argmax(cat_obs.mean(0)))
                word_best_bin = int(np.argmax(word_obs.mean(0)))
                n_epochs = cat_obs.shape[0]

                cat_obs_at_best  = cat_obs[:, cat_best_bin]
                cat_null_at_best = cat_null[:, cat_best_bin]
                word_obs_at_best  = word_obs[:, word_best_bin]
                word_null_at_best = word_null[:, word_best_bin]

                cat_null_mean  = float(cat_null.mean(0)[cat_best_bin])
                word_null_mean = float(word_null.mean(0)[word_best_bin])

                _, cat_pval  = stats.wilcoxon(
                    cat_obs_at_best - cat_null_at_best, alternative='greater')
                _, word_pval = stats.wilcoxon(
                    word_obs_at_best - word_null_at_best, alternative='greater')

            raw_records.append({
                'patient':        patient,
                'embedding':      emb,
                'model_type':     'semantic' if emb in SEM_MODELS else 'visual',
                'n_epochs':       n_epochs,
                'mean_cat_obs':   float(cat_obs_at_best.mean()),
                'mean_cat_null':  float(cat_null_mean),
                'cat_best_bin':   cat_best_bin,
                'cat_diff_mean':  float(cat_obs_at_best.mean() - cat_null_mean),
                'cat_pval_raw':   float(cat_pval),
                'mean_word_obs':  float(word_obs_at_best.mean()),
                'mean_word_null': float(word_null_mean),
                'word_best_bin':  word_best_bin,
                'word_diff_mean': float(word_obs_at_best.mean() - word_null_mean),
                'word_pval_raw':  float(word_pval),
            })

    df = pd.DataFrame(raw_records)
    if len(df) == 0:
        print("[Significance] No data found!")
        return df

    # Global Bonferroni correction across ALL patient x embedding tests
    n_tests = len(df)
    df['cat_pval_bonf']  = np.minimum(df['cat_pval_raw']  * n_tests, 1.0)
    df['word_pval_bonf'] = np.minimum(df['word_pval_raw'] * n_tests, 1.0)

    def _stars(p):
        if p < 0.001: return '***'
        if p < 0.01:  return '**'
        if p < 0.05:  return '*'
        return 'NS'

    df['cat_sig']      = df['cat_pval_bonf'].apply(_stars)
    df['word_sig']     = df['word_pval_bonf'].apply(_stars)
    df['cat_sig_raw']  = df['cat_pval_raw'].apply(_stars)
    df['word_sig_raw'] = df['word_pval_raw'].apply(_stars)

    n_cat  = (df['cat_sig']  != 'NS').sum()
    n_word = (df['word_sig'] != 'NS').sum()
    print(f"[Significance] Cat sig: {n_cat}/{n_tests} | Word sig: {n_word}/{n_tests}")
    return df
