"""One ROI vocabulary, and two independent maps into it.

**This module is what makes the two atlases peers rather than one being a subordinate of
the other.**  NMM and DK each parcellate the brain in their own words; this file names the
regions the *analysis* speaks in, and gives each atlas its own, separate mapping onto them.
Neither map consults the other, and neither atlas's scope is defined in terms of the other's
labels.  The names here are the ones that reach the figure legends and the ``nmm_roi`` /
``dk_roi`` columns of ``channels.pkl``.

What this replaces.  Agreement used to be scored by reducing NMM through
``label._CANONICAL`` and DK through ``surface.DK_CANONICAL`` into a third, coarser set of
comparison keys, with ``DK_MAY_SHARE`` policing the cases where two DK parcels collapsed
onto one key.  That machinery existed *because* there was no shared vocabulary.  With one,
agreement is ROI equality, and the invariant ``DK_MAY_SHARE`` was enforced by test is
structural instead: two parcels cannot silently become the same structure, because the ROI
each maps to is written down.

Three rules this file exists to keep:

1. **A label with no entry here has no ROI, and is therefore out of the analysis.**  The
   scope stays a whitelist for the reason ``AGENTS.md`` gives -- a new participant can carry
   parcels nobody has hit before, and under a blacklist those enter the analysis silently.
   Contacts still get a readable name (see :func:`roi_of`); what they do not get is
   membership.
2. **An unsplit parent parcel is not an ROI.**  ``Left MTG middle temporal gyrus`` maps to
   nothing: the vocabulary is ``aMTG``/``pMTG``, and a contact whose parcel was never split
   has no anterior/posterior call to report.  This matters for the one bilateral
   participant -- ``Right MTG middle temporal gyrus`` skips subdivision, because
   ``subdivide.SUBDIVISIONS`` is keyed on ``Left ...``, and it used to come back with an
   *empty* exclusion reason because :func:`config.strip_hemisphere` made it match the
   whitelist. Only the clinical exclusion kept those 27 contacts out of the analysis. Now
   the vocabulary keeps them out.
3. **Comparability is structural.**  A pair is comparable only when both ROIs are
   expressible by both atlases, so DK's ``pSTS`` and NMM's ``frontal operculum`` are
   reported as *not comparable* rather than as disagreements.  "The other atlas has no such
   parcel" and "the two atlases disagree" are different facts and are never pooled.

--------------------------------------------------------------------------------
VENDORED -- do not edit this file's vocabulary by hand.

Source   : Speech/electrode_labeling, `electrode_labeling/roi.py`
Commit   : 974dc0d7218b58c9bff4f888afed1f5cc9737d49  ("Make NMM and DK peers via a
           shared ROI vocabulary", 2026-08-08) plus **uncommitted working-tree changes**
           -- the 2026-08-23 `tp` -> `tpm` re-scope has not been committed in the sibling.
           Re-run the drift check after that commit lands.
Vendored : 2026-08-23, verbatim above the `EXCLUDED CONTACTS` banner below.

What changed on 2026-08-23: the analysis moved from `tp` (13 regions) to `tpm` (18).  The
five medial and deep regions -- entorhinal, parahippocampal, precuneus, insula, cingulate --
are now `in_analysis`, so `EXCLUDED_BY_REASON` no longer has a `medial` key at all.
`utils/roi_scopes.py` guarded on that key being non-empty and had to be reworked in the same
change.  `PALETTE_SCOPE` (23) is new: it is what the palette pins, deliberately wider than
the analysis so a `tpfm` figure has colours for its frontal regions.

Why a copy and not an import: `electrode_labeling` is a separate git repository on this
machine, not an installed package, and it needs nibabel/scipy/h5py plus the `N:` imaging
share that `main` has no reason to depend on.  This module is the part that needs none of
that -- pure stdlib, `typing.NamedTuple` only.

Why a copy and not a re-implementation: this exact table is what *generated* the `nmm_roi`
and `dk_roi` columns in `data/{PAT}/{PAT}_*channels.pkl`.  A second, hand-written table can
silently disagree with the one that produced the data, which would make both atlases
meaningless without anything failing.  `_index()` below raises if two labels claim one ROI,
so the copy is self-checking.

Drift is caught by `python scripts/check_roi_vocabulary.py --sibling <path>`; run it after
pulling either repository.  To change the vocabulary, edit the sibling, re-run its
`writeback` stage so the columns match, then re-vendor -- never the other way round.
--------------------------------------------------------------------------------
"""
from __future__ import annotations

from typing import NamedTuple


class ROI(NamedTuple):
    """One region in the analysis vocabulary, and how each atlas spells it."""

    name: str
    #: Palette family, or ``None`` for a region that is never given its own colour.
    family: str | None
    #: Rank within the family, anterior/ventral first.  Fixed, never derived from counts.
    order: int
    #: Why the analysis sets this region aside; ``""`` means it is in the analysis.
    reason: str
    #: The NMM labels that map here, post-merge and post-subdivision.
    nmm: tuple[str, ...]
    #: The DK labels that map here, post-merge and post-subdivision.
    dk: tuple[str, ...]

    @property
    def in_analysis(self) -> bool:
        return self.reason == ""

    @property
    def atlases(self) -> frozenset:
        return frozenset({a for a, labels in (("nmm", self.nmm), ("dk", self.dk)) if labels})


#: Reason strings.  The same group names the project already reports, so nothing downstream
#: has to learn a new vocabulary for why a region was dropped.
SENSORIMOTOR = "sensorimotor"
OCCIPITAL = "occipital"
AUDITORY_BELT = "auditory_belt"
SUBCORTICAL = "subcortical"
MEDIAL = "medial"
FRONTAL = "frontal"

#: Reported for a parcel that appears in neither list.  Not an error -- a parcel nobody has
#: hit before is a normal consequence of adding a participant -- but it must be visible.
UNSCOPED = "not_temporal_parietal"

# --------------------------------------------------------------------------- the table
#
# One row per ROI, with both atlases' spellings side by side.  Deliberately one table rather
# than two maps: the symmetry is then visible at a glance, and it is not possible to add a
# region to one atlas's vocabulary and forget the other's.
#
# An empty tuple on either side means that atlas has no parcel for the region, which is a
# fact about the atlases and drives :func:`comparable`.  It is never a placeholder for a
# mapping nobody got round to writing -- those two look identical from outside and mean
# opposite things, which is why every such gap carries a comment.

_TABLE: tuple[ROI, ...] = (
    # ---------------------------------------------------------------- in the analysis
    # Lateral temporal.  The a/p halves are minted by `subdivide.SUBDIVISIONS` on the NMM
    # side and `surface.DK_SUBDIVISIONS` on the DK side, under the same names on purpose,
    # so the two atlases' halves compare by string equality.  They are NOT the same
    # construction -- NMM's plane is each participant's own parcel centroid, DK's is one
    # fsaverage plane for the cohort -- and any a/p comparison has to carry that caveat.
    ROI("aMTG", "middle temporal", 0, "", ("aMTG",), ("aMTG",)),
    ROI("pMTG", "middle temporal", 1, "", ("pMTG",), ("pMTG",)),
    ROI("aSTG", "superior temporal", 0, "", ("aSTG",), ("aSTG",)),
    ROI("pSTG", "superior temporal", 1, "", ("pSTG",), ("pSTG",)),
    # DK's `bankssts`, renamed.  **NMM has no parcel for it** -- it divides the banks of the
    # superior temporal sulcus between STG and MTG -- so this is in the analysis on its own
    # anatomical merits (it is lateral temporal cortex, which is what the whitelist is
    # about) while being expressible by one atlas only.  That makes every pairing involving
    # it `not comparable`, which is the honest verdict: a vocabulary difference, not a
    # disagreement about where the contact is.
    ROI("pSTS", "superior temporal", 2, "", (), ("pSTS",)),
    ROI("aITG", "inferior temporal", 0, "", ("aITG",), ("aITG",)),
    ROI("pITG", "inferior temporal", 1, "", ("pITG",), ("pITG",)),
    ROI("aFus", "fusiform", 0, "", ("aFus",), ("aFus",)),
    ROI("pFus", "fusiform", 1, "", ("pFus",), ("pFus",)),
    ROI("temporal pole", "temporal pole", 0, "",
        ("Left TMP temporal pole",), ("temporalpole",)),
    # Lateral parietal.  `supramarginal` and `angular` are deliberately NOT related to each
    # other: both atlases draw an SMG/angular boundary, they just draw it in different
    # places, so a crossing is a real disagreement of exactly the aMTG/pMTG kind.  Relating
    # them is how DK's `inferiorparietal` once came to claim SMG and made the scoring
    # asymmetric.  DK's side of `angular` is `inferiorparietal`, already renamed by
    # `surface.DK_MERGES` -- see the note there for why that is not the classical IPL.
    ROI("supramarginal", "parietal", 0, "",
        ("Left SMG supramarginal gyrus",), ("supramarginal",)),
    ROI("angular", "parietal", 1, "", ("Left AnG angular gyrus",), ("angular",)),
    ROI("superior parietal", "dorsal parietal", 0, "",
        ("Left SPL superior parietal lobule",), ("superiorparietal",)),

    # ------------------------------------------- medial and deep cortex, added 2026-08-23
    # Moved into the analysis when the scope went from `tp` (13) to `tpm` (18).  Grouped the
    # way the meeting grouped it: insula is filed here because that is where the decision
    # put it, though anatomically it is deep and opercular rather than medial -- recorded as
    # decided rather than quietly reclassified.
    #
    # **This is where the two atlases stop being exact peers, and it is measured, not
    # assumed.**  DK has no subcortical parcels, so contacts NMM calls hippocampus, amygdala
    # or putamen land on the nearest cortex -- overwhelmingly `entorhinal`,
    # `parahippocampal` and `insula`.  Of the 307 contacts DK puts in these five regions,
    # 127 (41%) are ones NMM excludes as subcortical.  A DK-gated `tpm` analysis therefore
    # contains them while the NMM-gated one does not; the two arms no longer differ only in
    # the gate.  Reported per contact by `nmm_vs_dk_scope.csv`, never silently pooled.
    ROI("entorhinal", "medial temporal", 0, "",
        ("Left Ent entorhinal area",), ("entorhinal",)),
    ROI("parahippocampal", "medial temporal", 1, "",
        ("parahippocampal",), ("parahippocampal",)),
    # Its own family, **not** `dorsal parietal` beside `superior parietal`.  Anatomy allows
    # either -- both are superior parietal cortex -- but the palette's rule is one hue per
    # gyrus family, and precuneus is on the medial surface while SPL is on the dorsolateral
    # convexity.  The deciding factor was measured: joining `dorsal parietal` made it a
    # two-member family, which re-ran the shade ladder and moved `superior parietal` from
    # #7f5539 to #b59c8c -- with precuneus then taking #7f5539, i.e. inheriting the exact
    # colour a different region had in every previous figure.  A new hue leaves all 13
    # original colours byte-identical.
    ROI("precuneus", "medial parietal", 0, "", ("Left PCu precuneus",), ("precuneus",)),
    ROI("insula", "insula", 0, "", ("insula",), ("insula",)),
    ROI("cingulate", "cingulate", 0, "", ("cingulate",), ("cingulate",)),

    # ---------------------------------------------------------------------------- frontal
    ROI("orbitofrontal", "frontal", 0, FRONTAL, ("orbitofrontal",), ("orbitofrontal",)),
    ROI("IFG", "frontal", 1, FRONTAL, ("IFG",), ("IFG",)),
    ROI("middle frontal", "dorsal frontal", 0, FRONTAL,
        ("Left MFG middle frontal gyrus",), ("middlefrontal",)),
    ROI("superior frontal", "dorsal frontal", 1, FRONTAL,
        ("Left SFG superior frontal gyrus",), ("superiorfrontal",)),
    # DK has no frontal-operculum parcel: that cortex falls inside `parsopercularis` or
    # `insula` depending on where the contact sits.  Declared, not omitted.
    # Its own family rather than a third `frontal` member: joining `frontal` would drop the
    # palette's worst pair from 7.84 to 5.36 and re-shade orbitofrontal and IFG, whereas a
    # 13th hue leaves every existing colour untouched.  Only reachable under `tpfm`.
    ROI("frontal operculum", "operculum", 0, FRONTAL, ("Left FO frontal operculum",), ()),

    # ----------------------------------------------------------------------- sensorimotor
    ROI("precentral", None, 0, SENSORIMOTOR, ("Left PrG precentral gyrus",), ("precentral",)),
    ROI("postcentral", None, 1, SENSORIMOTOR,
        ("Left PoG postcentral gyrus",), ("postcentral",)),
    # NMM has no paracentral parcel; DK has no central-operculum or SMA parcel.  Both gaps
    # are real and both regions are out of scope anyway, so nothing is lost by either.
    ROI("paracentral", None, 2, SENSORIMOTOR, (), ("paracentral",)),
    ROI("central operculum", None, 3, SENSORIMOTOR, ("Left CO central operculum",), ()),
    ROI("supplementary motor", None, 4, SENSORIMOTOR,
        ("Left SMC supplementary motor cortex",), ()),

    # ---------------------------------------------------------------------- auditory belt
    # Excluding auditory cortex from a speech paper is a scope decision, not an oversight,
    # and belongs in the methods.  DK has no planum polare or planum temporale at all --
    # both are inside `superiortemporal` -- so DK's auditory-belt exclusion is necessarily
    # narrower than NMM's.  That asymmetry is in the atlases, not in this table.
    ROI("planum polare", None, 0, AUDITORY_BELT, ("Left PP planum polare",), ()),
    ROI("planum temporale", None, 1, AUDITORY_BELT, ("Left PT planum temporale",), ()),
    ROI("Heschl's", None, 2, AUDITORY_BELT,
        ("Left TTG transverse temporal gyrus",), ("transversetemporal",)),

    # -------------------------------------------------------------------------- occipital
    # `lingual` is the one judgement call: DK and NMM both place it in the occipital lobe,
    # but it is ventromedial and abuts fusiform, which is central to this paper.  Moving it
    # into the analysis means changing `reason` to "" here -- one edit, both atlases.
    ROI("lingual", None, 0, OCCIPITAL, ("Left LiG lingual gyrus",), ("lingual",)),
    ROI("calcarine", None, 1, OCCIPITAL,
        ("Left Calc calcarine cortex",), ("pericalcarine",)),
    ROI("cuneus", None, 2, OCCIPITAL, ("Left Cun cuneus",), ("cuneus",)),
    ROI("lateral occipital", None, 3, OCCIPITAL, (), ("lateraloccipital",)),
    ROI("middle occipital", None, 4, OCCIPITAL, ("Left MOG middle occipital gyrus",), ()),
    ROI("inferior occipital", None, 5, OCCIPITAL, ("Left IOG inferior occipital gyrus",), ()),
    ROI("superior occipital", None, 6, OCCIPITAL, ("Left SOG superior occipital gyrus",), ()),

    # ------------------------------------------------------------------------ subcortical
    # **DK has no subcortical parcels whatsoever** -- `aparc` is a surface atlas, and these
    # structures live in FreeSurfer's volumetric `aseg`.  That is not an omission here: it
    # is the reason the analysis being entirely cortical is what lets DK label the same
    # contacts NMM does.  A contact NMM calls hippocampus gets whatever cortex is nearest
    # from DK, which is why it must not be scored as DK disagreeing about hippocampus.
    ROI("Hippocampus", None, 0, SUBCORTICAL, ("Left Hippocampus",), ()),
    ROI("Amygdala", None, 1, SUBCORTICAL, ("Left Amygdala",), ()),
    ROI("Putamen", None, 2, SUBCORTICAL, ("Left Putamen",), ()),
    ROI("Caudate", None, 3, SUBCORTICAL, ("Left Caudate",), ()),
    ROI("Pallidum", None, 4, SUBCORTICAL, ("Left Pallidum",), ()),
    ROI("Accumbens Area", None, 5, SUBCORTICAL, ("Left Accumbens Area",), ()),
    ROI("Thalamus", None, 6, SUBCORTICAL, ("Left Thalamus Proper",), ()),
    ROI("Basal Forebrain", None, 7, SUBCORTICAL, ("Left Basal Forebrain",), ()),
)

BY_NAME: dict[str, ROI] = {roi.name: roi for roi in _TABLE}

#: The regions that can be given a colour, in table order.  A region with no family falls to
#: the `other` grey and `palette.propose` warns rather than inventing one, so growing the
#: palette stays a decision someone makes on purpose.
ROIS_WITH_FAMILY: tuple[ROI, ...] = tuple(r for r in _TABLE if r.family)

#: reason -> the ROIs dropped for it.  Derived, so it cannot drift from the table; it exists
#: because reports name the *groups* ("subcortical (Hippocampus, Amygdala, ...)") rather than
#: listing every region flat.
EXCLUDED_BY_REASON: dict[str, tuple[str, ...]] = {
    reason: tuple(r.name for r in _TABLE if r.reason == reason)
    for reason in dict.fromkeys(r.reason for r in _TABLE if r.reason)
}

#: In-analysis ROI names, in table order.  **The whitelist.**  18 regions: the lateral and
#: ventral temporal lobe, lateral parietal cortex, and the medial and deep cortex that
#: joined on 2026-08-23 when the scope moved from `tp` (13) to `tpm`.
IN_ANALYSIS: tuple[str, ...] = tuple(r.name for r in _TABLE if r.in_analysis)

#: Every region **any** supported scope can select: the analysis plus the frontal regions
#: `tpfm` adds.  23 names.
#:
#: This is what the palette pins, and it is deliberately wider than :data:`IN_ANALYSIS`.
#: Pinning only the analysis meant a figure drawn at `tpfm` rendered its frontal regions as
#: the reserved `other` grey -- the scope said "include these" and the palette had no colour
#: to offer.  Pinning the wider set costs nothing measurable: the worst CIEDE2000 pair in the
#: palette is 7.84 (`pSTG`/`pSTS`) at 13, 18 and 23 regions alike.
#:
#: What stops a figure naming a region it never drew is no longer this set -- it is
#: `palette.legend_entries(regions=...)`, which the figure calls with what it actually
#: plotted.  That check moved from pin time to draw time on purpose: pin time could only ever
#: guess which scope a future figure would use.
PALETTE_SCOPE: tuple[str, ...] = IN_ANALYSIS + EXCLUDED_BY_REASON.get(FRONTAL, ())


#: Marks a region on the non-default side.  Left is the default and unprefixed.
RIGHT_PREFIX = "Right "


def strip_hemisphere(label: str) -> str:
    for prefix in ("Left ", RIGHT_PREFIX):
        if label.startswith(prefix):
            return label[len(prefix):]
    return label


def _index(attr: str) -> dict[str, str]:
    """atlas label -> ROI, keyed **hemisphere-agnostically**.

    Both `Left PP planum polare` and the bare `PP planum polare` are stored, the same way
    :func:`subdivide.merge_map` already does it.  Without the bare key a right-hemisphere
    parcel misses the map, falls through to the raw string, and produces a *second spelling*
    of a region that already has one -- `PP planum polare` beside `planum polare` -- which
    would count as two regions in any table built from these columns.
    """
    out: dict[str, str] = {}
    for roi in _TABLE:
        for label in getattr(roi, attr):
            for key in {label, strip_hemisphere(label)}:
                if out.get(key, roi.name) != roi.name:
                    raise ValueError(f"{attr} label {key!r} maps to both "
                                     f"{out[key]!r} and {roi.name!r}")
                out[key] = roi.name
    return out


#: atlas label -> ROI name.  Built from :data:`_TABLE`, so the two cannot drift apart, and
#: raising on a duplicate is what stops one label quietly serving two regions.
NMM_TO_ROI: dict[str, str] = _index("nmm")
DK_TO_ROI: dict[str, str] = _index("dk")

_MAPS = {"nmm": NMM_TO_ROI, "dk": DK_TO_ROI}

#: ROI pairs that are neither equal nor a disagreement, declared once and symmetric.
#:
#: Kept deliberately short.  Most of what the old `DK_MAY_SHARE` had to declare is now
#: handled structurally by :func:`comparable` -- a region only one atlas can express is not
#: compared at all -- so what remains is genuine containment between two regions both
#: atlases *do* have.
RELATED: dict[frozenset, str] = {
    frozenset({"entorhinal", "parahippocampal"}):
        "entorhinal cortex sits on the parahippocampal gyrus -- genuine containment, and it "
        "holds whichever atlas said which",
}


def roi_of(label: str, atlas: str) -> str:
    """The ROI this atlas label belongs to, or a readable fallback name.

    **Left is the default and carries no prefix; a right-hemisphere region is written
    ``Right <roi>``.**  The cohort is left-only -- every participant but one, and that one's
    right shank was clinically excluded -- so a bare name means left and the prefix appears
    only where there is something to flag.

    That asymmetry is deliberate rather than cosmetic.  Merging the two sides would put
    right-hemisphere contacts into a left-hemisphere region's counts, silently; keeping the
    prefix means `Right planum polare` is **not** in :data:`BY_NAME`, so :func:`in_analysis`
    is false for it and :func:`exclusion_reason` reports :data:`UNSCOPED`.  Right-hemisphere
    contacts therefore cannot enter the analysis by accident, which is the decision
    ``AGENTS.md`` records: they are set aside rather than half-supported. Supporting them
    means adding the regions here on purpose, not relaxing this function.

    **Every labelled contact still gets a name**, including the ones the analysis sets
    aside -- that is the contract the ``nmm_roi`` / ``dk_roi`` columns rely on.  What an
    unmapped label does not get is membership.
    """
    text = str(label)
    mapping = _MAPS[atlas]
    if text in mapping:
        return mapping[text]
    bare = strip_hemisphere(text)
    # The index carries the bare key too, so this hits for any mapped region whatever side
    # it came from.  It misses only for labels deliberately absent from the table -- the
    # unsplit parents, e.g. `Right MTG middle temporal gyrus` -- which fall through to the
    # string itself and are reported as out of scope.
    name = mapping.get(bare, bare)
    return f"{RIGHT_PREFIX}{name}" if text.startswith(RIGHT_PREFIX) else name


def in_analysis(roi: str) -> bool:
    """Whether this ROI is in the analysis.  Unknown names are **out**, never in."""
    entry = BY_NAME.get(str(roi))
    return bool(entry and entry.in_analysis)


#: Written where an atlas found nothing to label the contact with.  Recognised here, not
#: only in :mod:`label`, because "the atlas found white matter" is **not** "this region is
#: out of scope" -- they are different states and the whitelist must not report the first as
#: the second.  `label.UNASSIGNED` and `config.UNASSIGNED` are the same string.
UNASSIGNED = "unassigned"


def exclusion_reason(roi: str) -> str:
    """Why this ROI is set aside, or ``""`` if it is in the analysis.

    A name absent from the table is excluded and reported as :data:`UNSCOPED`, so it is
    noticed rather than assumed.  :data:`UNASSIGNED` and the empty string are neither: the
    atlas had nothing to say, which `usage_for` classifies as `no_grey_label`.
    """
    name = str(roi)
    if name in (UNASSIGNED, ""):
        return ""
    entry = BY_NAME.get(name)
    if entry is None:
        return UNSCOPED
    return entry.reason


def expressible_by(roi: str) -> frozenset:
    entry = BY_NAME.get(str(roi))
    return entry.atlases if entry else frozenset()


def comparable(nmm_roi: str, dk_roi: str) -> bool:
    """Whether the two atlases can be asked to agree about this pair at all.

    Both ROIs must be in the vocabulary and expressible by both atlases.  DK's ``pSTS`` and
    NMM's ``frontal operculum`` therefore never enter the agreement rate: the other atlas
    has no parcel that could confirm or contradict them, and scoring that as a disagreement
    would count a difference between the atlases as an error in the labels.
    """
    both = frozenset({"nmm", "dk"})
    return expressible_by(nmm_roi) == both and expressible_by(dk_roi) == both


def agrees(nmm_roi: str, dk_roi: str) -> bool:
    """Whether the two atlases name the same region.

    Equality in the shared vocabulary, plus the declared containments in :data:`RELATED`.
    Symmetric by construction -- there is no direction in which one atlas's answer is the
    reference the other is scored against.  Pairs that are not :func:`comparable` are not
    disagreements and return ``True``; :func:`comparable` is what separates the two, and
    every report must carry both numbers.
    """
    if not comparable(nmm_roi, dk_roi):
        return True
    return str(nmm_roi) == str(dk_roi) or frozenset({str(nmm_roi), str(dk_roi)}) in RELATED

# ==============================================================================
#  EXCLUDED CONTACTS -- `main` addition, not part of the vendored vocabulary
# ==============================================================================
#
# Vendored from `electrode_labeling/config.py:161-170` at the same commit.  These are
# exclusions by contact NAME, which the ROI vocabulary cannot express: the reason is a fact
# about the recording, not about the region.
#
# They matter most under DK.  `nmm_roi` writes right-hemisphere regions as `Right <roi>`,
# which is deliberately absent from `BY_NAME`, so :func:`in_analysis` already keeps them out
# -- applying this map under NMM is a verified no-op (643 -> 643 contacts).  `dk_roi` comes
# from the rh fsaverage annotation and carries **no side prefix at all**, so PV's right-shank
# contacts read as ordinary `aMTG` / `aSTG` / `aFus` and would enter a left-hemisphere
# analysis silently.  Verified 2026-08-08: this map removes exactly 9 of them (702 -> 693).
#
# Apply it under BOTH atlases regardless.  That is what makes "the two arms differ only in
# the gate" literally true rather than approximately true.

EXCLUDED_CONTACTS: dict = {
    "EH": ("W16", "W17", "W18"),
    "PV": ("RA1", "RA2", "RA3", "RA4", "RA5", "RA10", "RA11", "RA12", "RA13",
           "RB1", "RB2", "RB3", "RB4", "RB10", "RB11", "RB12"),
}

EXCLUDED_REASON: dict = {
    "EH": "W16-W18 recorded but not localised: LeGUI's W shank stops at W15",
    "PV": "RA/RB shanks are right-hemisphere; this cohort is left-only",
}

#: The column each atlas name lives in, in `data/{PAT}/{PAT}_*channels.pkl`.
ATLAS_COLUMN: dict = {"nmm": "nmm_roi", "dk": "dk_roi"}


def excluded_contacts(patient: str) -> frozenset:
    """Contact names set aside for *patient*, by name.  Empty for most patients."""
    return frozenset(EXCLUDED_CONTACTS.get(str(patient), ()))
