#!/usr/bin/env python
"""Mirror the canonical shared skills into Claude Code's discovery directory.

Codex reads repo skills from ``.agents/skills/`` natively; Claude Code reads only
``.claude/skills/``. ``.agents/skills/`` is therefore the single canonical source and
``.claude/skills/`` is generated from it by this script.

A copy rather than a symlink or junction: git ``core.symlinks`` is false on the primary
workstation, and reparse points inside the OneDrive-synced tree behave inconsistently.
``.claude/`` is gitignored, so the mirror never reaches git and is rebuilt per machine.

Claude-only SKILL.md frontmatter keys (``user-invocable``, ``argument-hint``, …) live in
``<skill>/platform/claude.frontmatter.yaml`` and are merged into the mirrored SKILL.md, so
the canonical file stays portable to Codex.

Usage
-----
    python scripts/sync_agent_skills.py            # write the mirror
    python scripts/sync_agent_skills.py --check    # report drift, write nothing, exit 1

Stdlib only, by design: this must run in a bare checkout before any environment exists.
"""

from __future__ import annotations

import argparse
import filecmp
import shutil
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
SRC_ROOT = REPO / ".agents" / "skills"
DST_ROOT = REPO / ".claude" / "skills"

PLATFORM_DIR = "platform"
CLAUDE_FRONTMATTER = "claude.frontmatter.yaml"

BANNER = (
    "<!-- GENERATED by scripts/sync_agent_skills.py from "
    ".agents/skills/{name}/ — do not edit; edits here are lost on the next sync -->\n"
)


def split_frontmatter(text: str) -> tuple[list[str], str]:
    """Return (frontmatter lines without the --- fences, remaining body)."""
    lines = text.lstrip("﻿").splitlines(keepends=True)
    if not lines or lines[0].strip() != "---":
        return [], text
    for i in range(1, len(lines)):
        if lines[i].strip() == "---":
            return lines[1:i], "".join(lines[i + 1 :])
    return [], text


def read_platform_keys(skill_dir: Path) -> list[str]:
    """Claude-only frontmatter lines to graft on, comments and blanks stripped."""
    path = skill_dir / PLATFORM_DIR / CLAUDE_FRONTMATTER
    if not path.is_file():
        return []
    out = []
    for line in path.read_text(encoding="utf-8").splitlines():
        stripped = line.strip()
        if stripped and not stripped.startswith("#"):
            out.append(line.rstrip() + "\n")
    return out


def render_skill_md(skill_dir: Path) -> str:
    """The SKILL.md that belongs in the mirror: banner + merged frontmatter + body."""
    name = skill_dir.name
    text = (skill_dir / "SKILL.md").read_text(encoding="utf-8")
    front, body = split_frontmatter(text)
    extra = read_platform_keys(skill_dir)
    if not front:
        # No frontmatter to merge into; leave the file alone but still mark it generated.
        return BANNER.format(name=name) + text
    merged = ["---\n", *front, *extra, "---\n"]
    return BANNER.format(name=name) + "".join(merged) + body


def planned_files(skill_dir: Path) -> dict[Path, str | None]:
    """Map of destination-relative path -> rendered text (None means copy bytes)."""
    plan: dict[Path, str | None] = {}
    for src in skill_dir.rglob("*"):
        if not src.is_file():
            continue
        rel = src.relative_to(skill_dir)
        if rel.parts and rel.parts[0] == PLATFORM_DIR:
            continue  # platform/ is source-side only
        plan[rel] = render_skill_md(skill_dir) if rel.as_posix() == "SKILL.md" else None
    return plan


def sync(check_only: bool) -> int:
    if not SRC_ROOT.is_dir():
        print(f"FAIL  canonical skill directory missing: {SRC_ROOT}", file=sys.stderr)
        return 1

    skills = sorted(d for d in SRC_ROOT.iterdir() if d.is_dir())
    drift: list[str] = []
    written = 0

    for skill_dir in skills:
        if not (skill_dir / "SKILL.md").is_file():
            print(f"FAIL  {skill_dir.relative_to(REPO)} has no SKILL.md", file=sys.stderr)
            return 1

        dst_dir = DST_ROOT / skill_dir.name
        plan = planned_files(skill_dir)

        for rel, text in sorted(plan.items()):
            dst = dst_dir / rel
            src = skill_dir / rel
            if text is None:
                same = dst.is_file() and filecmp.cmp(src, dst, shallow=False)
            else:
                same = dst.is_file() and dst.read_text(encoding="utf-8") == text
            if same:
                continue
            drift.append(str(dst.relative_to(REPO)))
            if check_only:
                continue
            dst.parent.mkdir(parents=True, exist_ok=True)
            if text is None:
                shutil.copy2(src, dst)
            else:
                # newline="" keeps the source's own line endings; Path.write_text cannot
                # pass it on the Python 3.9 in the Speech env.
                with open(dst, "w", encoding="utf-8", newline="") as fh:
                    fh.write(text)
            written += 1

        # Stale files inside a still-existing skill.
        if dst_dir.is_dir():
            for existing in sorted(dst_dir.rglob("*")):
                if not existing.is_file():
                    continue
                if existing.relative_to(dst_dir) not in plan:
                    drift.append(f"{existing.relative_to(REPO)} (orphan)")
                    if not check_only:
                        existing.unlink()

    # Whole skills that no longer have a canonical source.
    if DST_ROOT.is_dir():
        names = {d.name for d in skills}
        for stale in sorted(d for d in DST_ROOT.iterdir() if d.is_dir()):
            if stale.name not in names:
                drift.append(f"{stale.relative_to(REPO)} (orphan skill)")
                if not check_only:
                    shutil.rmtree(stale)

    if check_only:
        if drift:
            print("DRIFT  .claude/skills/ is out of sync with .agents/skills/:")
            for item in drift:
                print(f"       {item}")
            print("       fix: python scripts/sync_agent_skills.py")
            return 1
        print(f"OK     .claude/skills/ matches .agents/skills/ ({len(skills)} skills)")
        return 0

    print(f"synced {len(skills)} skills -> {DST_ROOT.relative_to(REPO)}")
    for skill_dir in skills:
        extra = " (+claude frontmatter)" if read_platform_keys(skill_dir) else ""
        print(f"       {skill_dir.name}{extra}")
    if drift:
        print(f"       {written} file(s) written, {len(drift) - written} removed")
    else:
        print("       already up to date")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--check",
        action="store_true",
        help="report drift and exit 1 without writing anything",
    )
    args = parser.parse_args()
    return sync(check_only=args.check)


if __name__ == "__main__":
    sys.exit(main())
